//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class INinboundPlan
    {
        public long ID { get; set; }
        public string InboundPlanCode { get; set; }
        public string SiteCode { get; set; }
        public string CodeOwner { get; set; }
        public System.DateTime InboundPlanDate { get; set; }
        public string CodeSupplier { get; set; }
        public string SlipClass { get; set; }
        public System.DateTime SlipDate { get; set; }
        public string SlipNo { get; set; }
        public string CodeClassInbound { get; set; }
        public string InboundStatus { get; set; }
        public string PrintStatus { get; set; }
        public string Remarks { get; set; }
        public bool Is_Deleted { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
