//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mItemUnit
    {
        public long ID { get; set; }
        public string ItemCode { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> QtyperCase { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> gwkg { get; set; }
        public Nullable<decimal> nwkg { get; set; }
        public Nullable<decimal> slcm { get; set; }
        public Nullable<decimal> swcm { get; set; }
        public Nullable<decimal> shcm { get; set; }
        public Nullable<decimal> MaintainingQty { get; set; }
        public bool Is_Deleted { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
