//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBallocation
    {
        public long ID { get; set; }
        public string OutboundPlanNo { get; set; }
        public string OutboundDetailNo { get; set; }
        public string StockCode { get; set; }
        public string StockDetailCode { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<decimal> QtyCase { get; set; }
        public Nullable<decimal> QtyInnerCase { get; set; }
        public Nullable<decimal> QtyUnit { get; set; }
        public bool Is_Deleted { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
