//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBoutboundPlan
    {
        public long ID { get; set; }
        public string OutboundPlanNo { get; set; }
        public string SiteCode { get; set; }
        public string CodeOwner { get; set; }
        public System.DateTime OutboundPlanDate { get; set; }
        public System.DateTime DeliveryPlanDate { get; set; }
        public System.DateTime ShipoutDate { get; set; }
        public string ShipToCode { get; set; }
        public string BillToCode { get; set; }
        public string ShipperCode { get; set; }
        public string BuyerCode { get; set; }
        public string ConsigneeCode { get; set; }
        public string UrgentFlagCode { get; set; }
        public string TransportClassCode { get; set; }
        public string OutboundClassCode { get; set; }
        public string OutboundStatus { get; set; }
        public System.DateTime SlipDate { get; set; }
        public string SlipNo { get; set; }
        public string SlipClass { get; set; }
        public string SlipRemarks { get; set; }
        public string DEClass { get; set; }
        public bool PrintFlag { get; set; }
        public bool Is_Deleted { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
