//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class STstockInventoryDetail
    {
        public long ID { get; set; }
        public string StockCode { get; set; }
        public string StockDetailCode { get; set; }
        public string ItemCode { get; set; }
        public string PONo { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<System.DateTime> InboundDate { get; set; }
        public string LocationCode { get; set; }
        public string LocationSubCode { get; set; }
        public string InboundPlanNo { get; set; }
        public string InboundNoResult { get; set; }
        public string InboundDetailNo { get; set; }
        public decimal ActualStockQty { get; set; }
        public Nullable<decimal> AllocatedQty { get; set; }
        public Nullable<decimal> PickedQty { get; set; }
        public string SupplierCode { get; set; }
        public string OriginalItemCode { get; set; }
        public decimal CaseQty { get; set; }
        public decimal QtyPerCase { get; set; }
        public decimal InnerCaseQty { get; set; }
        public decimal InnerQtyPerCase { get; set; }
        public decimal UnitQty { get; set; }
        public Nullable<decimal> NW { get; set; }
        public Nullable<decimal> GW { get; set; }
        public Nullable<decimal> M3 { get; set; }
        public Nullable<System.DateTime> LastInboundDate { get; set; }
        public Nullable<System.DateTime> LastOutboundDate { get; set; }
        public string SlipClass { get; set; }
        public Nullable<System.DateTime> SlipDate { get; set; }
        public string SlipNo { get; set; }
        public string SlipRemarks { get; set; }
        public bool Is_Deleted { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
