//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSv2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WMSv2Entities : DbContext
    {
        public WMSv2Entities()
            : base("name=WMSv2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INinboundItem> INinboundItems { get; set; }
        public virtual DbSet<INinboundPlan> INinboundPlans { get; set; }
        public virtual DbSet<INinboundSet> INinboundSets { get; set; }
        public virtual DbSet<mCode> mCodes { get; set; }
        public virtual DbSet<mCodeBack> mCodeBacks { get; set; }
        public virtual DbSet<mCustomerSupplier> mCustomerSuppliers { get; set; }
        public virtual DbSet<mItem> mItems { get; set; }
        public virtual DbSet<mItemCategory> mItemCategories { get; set; }
        public virtual DbSet<mItemConversion> mItemConversions { get; set; }
        public virtual DbSet<mItemPrice> mItemPrices { get; set; }
        public virtual DbSet<mItemSupplier> mItemSuppliers { get; set; }
        public virtual DbSet<mItemUnit> mItemUnits { get; set; }
        public virtual DbSet<mLocation> mLocations { get; set; }
        public virtual DbSet<mLocationSub> mLocationSubs { get; set; }
        public virtual DbSet<mSite> mSites { get; set; }
        public virtual DbSet<mUser> mUsers { get; set; }
        public virtual DbSet<OBallocation> OBallocations { get; set; }
        public virtual DbSet<OBoutboundItem> OBoutboundItems { get; set; }
        public virtual DbSet<OBoutboundPlan> OBoutboundPlans { get; set; }
        public virtual DbSet<OBpicking> OBpickings { get; set; }
        public virtual DbSet<STstockInventory> STstockInventories { get; set; }
        public virtual DbSet<STstockInventoryDetail> STstockInventoryDetails { get; set; }
    
        public virtual int COMPUTE_Picked(string outboundPlanNo, string outboundDetailNo)
        {
            var outboundPlanNoParameter = outboundPlanNo != null ?
                new ObjectParameter("OutboundPlanNo", outboundPlanNo) :
                new ObjectParameter("OutboundPlanNo", typeof(string));
    
            var outboundDetailNoParameter = outboundDetailNo != null ?
                new ObjectParameter("OutboundDetailNo", outboundDetailNo) :
                new ObjectParameter("OutboundDetailNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COMPUTE_Picked", outboundPlanNoParameter, outboundDetailNoParameter);
        }
    
        public virtual ObjectResult<GET_InboundItemsinbound_Result> GET_InboundItemsinbound(string inboundPlanCode)
        {
            var inboundPlanCodeParameter = inboundPlanCode != null ?
                new ObjectParameter("InboundPlanCode", inboundPlanCode) :
                new ObjectParameter("InboundPlanCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_InboundItemsinbound_Result>("GET_InboundItemsinbound", inboundPlanCodeParameter);
        }
    
        public virtual ObjectResult<GET_InboundItemsinboundSet_Result> GET_InboundItemsinboundSet(string inboundPlanCode)
        {
            var inboundPlanCodeParameter = inboundPlanCode != null ?
                new ObjectParameter("InboundPlanCode", inboundPlanCode) :
                new ObjectParameter("InboundPlanCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_InboundItemsinboundSet_Result>("GET_InboundItemsinboundSet", inboundPlanCodeParameter);
        }
    
        public virtual ObjectResult<GET_StockInboundDetailed_Result> GET_StockInboundDetailed()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_StockInboundDetailed_Result>("GET_StockInboundDetailed");
        }
    
        public virtual ObjectResult<GET_OutboundItemsAllocated_Result> GET_OutboundItemsAllocated(string outboundPlanCode)
        {
            var outboundPlanCodeParameter = outboundPlanCode != null ?
                new ObjectParameter("OutboundPlanCode", outboundPlanCode) :
                new ObjectParameter("OutboundPlanCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_OutboundItemsAllocated_Result>("GET_OutboundItemsAllocated", outboundPlanCodeParameter);
        }
    
        public virtual ObjectResult<GET_OutboundItems_Result> GET_OutboundItems(string outboundPlanCode)
        {
            var outboundPlanCodeParameter = outboundPlanCode != null ?
                new ObjectParameter("OutboundPlanCode", outboundPlanCode) :
                new ObjectParameter("OutboundPlanCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_OutboundItems_Result>("GET_OutboundItems", outboundPlanCodeParameter);
        }
    
        public virtual ObjectResult<GET_Outbound_PickedItems_Result> GET_Outbound_PickedItems(string outboundPlanCode)
        {
            var outboundPlanCodeParameter = outboundPlanCode != null ?
                new ObjectParameter("OutboundPlanCode", outboundPlanCode) :
                new ObjectParameter("OutboundPlanCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_Outbound_PickedItems_Result>("GET_Outbound_PickedItems", outboundPlanCodeParameter);
        }
    
        public virtual ObjectResult<GET_StockInbound_Result> GET_StockInbound()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_StockInbound_Result>("GET_StockInbound");
        }
    }
}
